server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      
  datasource: 
    url: jdbc:h2:file:~/coffeestore
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop