server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      
  datasource: 
    url: jdbc:h2:file:~/coffeestore
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

order:
  type:
    beans:
      espresso:  10
      cappacino:  12
    milk:
      espresso:  10
      cappacino:  12
      
machine:
  config:
    milk:  10
    beans:  10